applicationConfiguration:
  databaseConfiguration:
    host: ${DATABASE_HOST:localhost}
    port: ${DATABASE_PORT:5432}
    user: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    name: ${DATABASE_NAME:postgres}
    minOpenConns: 5
    maxOpenConns: 10
    schema: ${DATABASE_SCHEMA:public}
    statementCacheCapacity: 128
    ConnTimeout: 3s
    MaxOpenConnTTL: 30m
    MaxIdleConnTTL: 10m
    MaxConnLifetimeJitterTT: "10%"
  serverConfiguration:
    port: 8080
  corsConfiguration:
    hostname: "${CORS_CONFIGURATION_HOST_NAME:http://localhost:3000}"
  googleSSOConfiguration:
    clientID: ${GOOGLE_SSO_CLIENT_ID}